### PR TITLE
Implement named date ranges as report filters

### PR DESCRIPTION
**Pull request by jasonperrone**
Brian,

This implements named date ranges, **but** temporarily *de-implements* custom date ranges. The reason is this:  The framework as you know supports a DateRange being either an array of actual dates or a string which is a named date range. I want to take full advantage of that, but I'm having a hard time getting the HTML to support it. 

In the HTML, I have a select box which is the date_range filter and it sends a string to the controller containing the named date range. So, the framework perfectly handles that. But, I have learned that I cannot have other elements with the same name except as an array. For example, having a select list with a name like [report][context][date_range] and then having inputs like [report][context][date_range][], which is the from and to. If all of those elements get submitted together it crashes. The tricky part then is for me to use JavaScript magic to make sure either the select box get submitted OR the two inputs get submitted, but not both. So yeah, we can easily say that if the select box is anything but manual, then we disable the two text boxes and they won't get submitted. Not bad. The harder part is when the select box is manual and the from and to inputs are enabled. I can't very well disable the select box or you couldn't change back from manual again. So, it's almost like I have to intercept the submit and remove the select box from the form parameters before I allow the post to reach the controller. It seems so ugly and I am sure there is a better way, but I am hitting the ceiling of my current knowledge when it comes to JavaScript processing of forms.

Anyway, that's why I am sending this in. Right now it is working like other apps we're familiar with, which ONLY support named date ranges. I have to come back to manual range once I have a good plan.

### CODE REVIEW

**Comment by bdeterling** [comment]
I might be missing something, but why not just use the array syntax for all three and the figure it out on the server? What is the crash? app/models/date_range.rb would have to be changed to handle three parameters instead of one, but I'm not sure what else would need to change.

**Comment by jasonperrone** [comment]
I didn't want to figure it out on the server, mainly because of what you said yesterday about "it can be a string or it can be an array" and the server doesn't need to know which. If I knew changing DateRange's initialize method was an option for you, then yeah it would be more straightforward. You made it sound like nothing on the server should need to change, and merely have the form submit either a string or an array.

**Comment by bdeterling** [comment]
You have my blessing to change the server code. When I wrote that I was thinking there would be two widgets, but we can change it to assume one widget with a one or three element array. It’s up to you if you want to still support a string only option, but I can’t think of when we would use it.

**Comment by jasonperrone** [comment]
Ok, don't merge this. I'll update the PR.

**Comment by jasonperrone** [comment]
@bdeterling Pull request updated.

**Comment by bdeterling** [comment]
Will need to make the date formats configurable, but looks good.

**Pull request merged**
